spring:
  application:
    name: MyList
  profiles:
    include: prod
  datasource:
    url: jdbc:mysql://localhost:3306/mylist?serverTimezone=UTC&characterEncoding=utf-8
    username: mylist
    password: 1234567
