spring:
  application:
    name: MyList
  profiles:
    include: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/mylist
    username: mylist
    password: 1234567

mybatis:
    config-location: classpath:config/mybatis.xml
    mapper-locations: classpath:mapper/*.xml
