spring:
  application:
    name: MyList
  profiles:
    include: prod
  datasource:
    url: jdbc:mysql://localhost:3306/mylist2?serverTimezone=UTC&characterEncoding=utf-8&noAccessToProcedureBodies=true
    username: mylist
    password: 1234567

mybatis:
    config-location: classpath:config/mybatis.xml
    mapper-locations: classpath:mapper/*.xml

