spring:
    application:
        name: MyList
    profiles:
        include: prod
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: test
        password: 1234567
